// AUTO-GENERATED by tmp/gen_data.py — do not edit by hand.

export type ReserveKind = 'clean' | 'dirty'
export type AblationRow = {
  reserve: ReserveKind
  order: string
  extra: number
  cleanBytes: number
  dirtyBytes: number
  spills: number
}

export const SYNTH_ABLATION: AblationRow[] = [
  { reserve: 'clean', order: 'capfit_id', extra: 1536, cleanBytes: 1536, dirtyBytes: 0, spills: 3 },
  { reserve: 'clean', order: 'p1', extra: 3328, cleanBytes: 3328, dirtyBytes: 0, spills: 9 },
  { reserve: 'clean', order: 'id_raw', extra: 1536, cleanBytes: 1536, dirtyBytes: 0, spills: 3 },
  { reserve: 'clean', order: 'min_id', extra: 2560, cleanBytes: 2560, dirtyBytes: 0, spills: 5 },
  { reserve: 'dirty', order: 'capfit_id', extra: 3072, cleanBytes: 0, dirtyBytes: 3072, spills: 3 },
  { reserve: 'dirty', order: 'p1', extra: 4864, cleanBytes: 1792, dirtyBytes: 3072, spills: 10 },
  { reserve: 'dirty', order: 'id_raw', extra: 3072, cleanBytes: 0, dirtyBytes: 3072, spills: 3 },
  { reserve: 'dirty', order: 'min_id', extra: 5120, cleanBytes: 0, dirtyBytes: 5120, spills: 5 },
]
