// AUTO-GENERATED by tmp/gen_data.py — do not edit by hand.

export type ProblemId = 1 | 2 | 3
export type CaseFamily = 'matmul' | 'fa' | 'conv'
export type ResultKind = 'WIN' | 'LOSS'
export type Metric = { maxL1: number; maxUB: number; spills: number; extra: number; time: number }
export type HeadlineRow = {
  case: string
  family: CaseFamily
  problem: ProblemId
  result: ResultKind
  ours: Metric
  base: Metric
}

export const HEADLINE: HeadlineRow[] = [
  { case: 'Conv_Case0', family: 'conv', problem: 1, result: 'WIN', ours: { maxL1: 6912, maxUB: 0, spills: 0, extra: 0, time: 394430 }, base: { maxL1: 7488, maxUB: 0, spills: 0, extra: 0, time: 359570 } },
  { case: 'Conv_Case0', family: 'conv', problem: 2, result: 'LOSS', ours: { maxL1: 6912, maxUB: 0, spills: 339, extra: 88044, time: 615694 }, base: { maxL1: 7488, maxUB: 0, spills: 141, extra: 73500, time: 535312 } },
  { case: 'Conv_Case0', family: 'conv', problem: 3, result: 'LOSS', ours: { maxL1: 6912, maxUB: 0, spills: 342, extra: 92652, time: 553280 }, base: { maxL1: 7488, maxUB: 0, spills: 141, extra: 73500, time: 535312 } },
  { case: 'Conv_Case1', family: 'conv', problem: 1, result: 'WIN', ours: { maxL1: 13786, maxUB: 0, spills: 0, extra: 0, time: 650044 }, base: { maxL1: 14040, maxUB: 0, spills: 0, extra: 0, time: 573395 } },
  { case: 'Conv_Case1', family: 'conv', problem: 2, result: 'WIN', ours: { maxL1: 14040, maxUB: 0, spills: 1963, extra: 72520, time: 1159169 }, base: { maxL1: 14040, maxUB: 0, spills: 1828, extra: 73240, time: 1150333 } },
  { case: 'Conv_Case1', family: 'conv', problem: 3, result: 'LOSS', ours: { maxL1: 14040, maxUB: 0, spills: 1951, extra: 73578, time: 1111778 }, base: { maxL1: 14040, maxUB: 0, spills: 1290, extra: 86690, time: 1073322 } },
  { case: 'FlashAttention_Case0', family: 'fa', problem: 1, result: 'WIN', ours: { maxL1: 256, maxUB: 8258, spills: 0, extra: 0, time: 31063 }, base: { maxL1: 3328, maxUB: 1428, spills: 0, extra: 0, time: 31429 } },
  { case: 'FlashAttention_Case0', family: 'fa', problem: 2, result: 'LOSS', ours: { maxL1: 3328, maxUB: 1428, spills: 31, extra: 3904, time: 51700 }, base: { maxL1: 3328, maxUB: 1428, spills: 41, extra: 3692, time: 53374 } },
  { case: 'FlashAttention_Case0', family: 'fa', problem: 3, result: 'WIN', ours: { maxL1: 4096, maxUB: 1510, spills: 58, extra: 5832, time: 46167 }, base: { maxL1: 3328, maxUB: 1428, spills: 24, extra: 4128, time: 46761 } },
  { case: 'FlashAttention_Case1', family: 'fa', problem: 1, result: 'WIN', ours: { maxL1: 256, maxUB: 33010, spills: 0, extra: 0, time: 112458 }, base: { maxL1: 5376, maxUB: 2468, spills: 0, extra: 0, time: 113445 } },
  { case: 'FlashAttention_Case1', family: 'fa', problem: 2, result: 'LOSS', ours: { maxL1: 5376, maxUB: 2468, spills: 229, extra: 32920, time: 214361 }, base: { maxL1: 5376, maxUB: 2468, spills: 146, extra: 32840, time: 193059 } },
  { case: 'FlashAttention_Case1', family: 'fa', problem: 3, result: 'WIN', ours: { maxL1: 5376, maxUB: 2468, spills: 229, extra: 34432, time: 180364 }, base: { maxL1: 5376, maxUB: 2468, spills: 146, extra: 32840, time: 193059 } },
  { case: 'Matmul_Case0', family: 'matmul', problem: 1, result: 'WIN', ours: { maxL1: 128, maxUB: 0, spills: 0, extra: 0, time: 82308 }, base: { maxL1: 9216, maxUB: 0, spills: 0, extra: 0, time: 82773 } },
  { case: 'Matmul_Case0', family: 'matmul', problem: 2, result: 'WIN', ours: { maxL1: 9216, maxUB: 0, spills: 271, extra: 34688, time: 192380 }, base: { maxL1: 9216, maxUB: 0, spills: 273, extra: 34944, time: 194331 } },
  { case: 'Matmul_Case0', family: 'matmul', problem: 3, result: 'WIN', ours: { maxL1: 9216, maxUB: 0, spills: 273, extra: 34944, time: 186820 }, base: { maxL1: 9216, maxUB: 0, spills: 273, extra: 34944, time: 194331 } },
  { case: 'Matmul_Case1', family: 'matmul', problem: 1, result: 'WIN', ours: { maxL1: 128, maxUB: 0, spills: 0, extra: 0, time: 629076 }, base: { maxL1: 34816, maxUB: 0, spills: 0, extra: 0, time: 583525 } },
  { case: 'Matmul_Case1', family: 'matmul', problem: 2, result: 'WIN', ours: { maxL1: 34816, maxUB: 0, spills: 3600, extra: 460800, time: 1783145 }, base: { maxL1: 34816, maxUB: 0, spills: 3600, extra: 460800, time: 1800218 } },
  { case: 'Matmul_Case1', family: 'matmul', problem: 3, result: 'WIN', ours: { maxL1: 34816, maxUB: 0, spills: 3601, extra: 460928, time: 1771132 }, base: { maxL1: 34816, maxUB: 0, spills: 3600, extra: 460800, time: 1800218 } },
]

export const CASES: string[] = ['Conv_Case0', 'Conv_Case1', 'FlashAttention_Case0', 'FlashAttention_Case1', 'Matmul_Case0', 'Matmul_Case1']

export const FAMILY_COLOR: Record<CaseFamily, string> = {
  matmul: '#0072b2',
  fa: '#cc79a7',
  conv: '#e69f00',
}

export const HEADLINE_STATS = {
  total: 18,
  valid: 18,
  wins: 13,
  losses: 5,
  p1Wins: 6,
  p1Total: 6,
} as const
