// AUTO-GENERATED by tmp/gen_data.py — do not edit by hand.

export type OrderKind = 'p1' | 'phi_best'
export type MisalignRow = {
  case: string
  family: 'matmul' | 'fa' | 'conv'
  orderKind: OrderKind
  maxL1: number
  maxUB: number
  overRatio: number
}

export const MISALIGN: MisalignRow[] = [
  { case: 'Conv_Case0', family: 'conv', orderKind: 'p1', maxL1: 6912, maxUB: 0, overRatio: 1.6875 },
  { case: 'Conv_Case0', family: 'conv', orderKind: 'phi_best', maxL1: 9360, maxUB: 0, overRatio: 2.28515625 },
  { case: 'Conv_Case1', family: 'conv', orderKind: 'p1', maxL1: 13786, maxUB: 0, overRatio: 20.5625 },
  { case: 'Conv_Case1', family: 'conv', orderKind: 'phi_best', maxL1: 14040, maxUB: 0, overRatio: 3.427734375 },
  { case: 'FlashAttention_Case0', family: 'fa', orderKind: 'p1', maxL1: 256, maxUB: 8258, overRatio: 8.064453125 },
  { case: 'FlashAttention_Case0', family: 'fa', orderKind: 'phi_best', maxL1: 3328, maxUB: 1428, overRatio: 1.39453125 },
  { case: 'FlashAttention_Case1', family: 'fa', orderKind: 'p1', maxL1: 256, maxUB: 33010, overRatio: 32.236328125 },
  { case: 'FlashAttention_Case1', family: 'fa', orderKind: 'phi_best', maxL1: 5376, maxUB: 2468, overRatio: 2.41015625 },
  { case: 'Matmul_Case0', family: 'matmul', orderKind: 'p1', maxL1: 128, maxUB: 0, overRatio: 1.75 },
  { case: 'Matmul_Case0', family: 'matmul', orderKind: 'phi_best', maxL1: 9216, maxUB: 0, overRatio: 2.25 },
  { case: 'Matmul_Case1', family: 'matmul', orderKind: 'p1', maxL1: 128, maxUB: 0, overRatio: 15.0 },
  { case: 'Matmul_Case1', family: 'matmul', orderKind: 'phi_best', maxL1: 34816, maxUB: 0, overRatio: 8.5 },
]
