// AUTO-GENERATED by tmp/gen_data.py — do not edit by hand.

export type VictimPoint = { victim: string; extra: number }
export type OrderBlock = {
  order: string
  cv: number
  extraMin: number
  extraMax: number
  byVictim: VictimPoint[]
}
export type OrderVictimCase = {
  case: string
  family: 'matmul' | 'fa' | 'conv'
  orders: OrderBlock[]
}

export const VICTIMS: string[] = ['dist_size_cost', 'cost_then_dist', 'cheap_first', 'far_only']
export const ORDER_KEYS: string[] = ['p1', 'capfit_id', 'id_raw', 'min_id', 'baseline']

export const ORDER_VICTIM: OrderVictimCase[] = [
  { case: 'Conv_Case0', family: 'conv', orders: [
      { order: 'p1', cv: 0.0, extraMin: 88044, extraMax: 88044, byVictim: [{ victim: 'dist_size_cost', extra: 88044 }, { victim: 'cost_then_dist', extra: 88044 }, { victim: 'cheap_first', extra: 88044 }, { victim: 'far_only', extra: 88044 }] },
      { order: 'capfit_id', cv: 0.00943330191123077, extraMin: 121048, extraMax: 123880, byVictim: [{ victim: 'dist_size_cost', extra: 121048 }, { victim: 'cost_then_dist', extra: 123880 }, { victim: 'cheap_first', extra: 123880 }, { victim: 'far_only', extra: 123160 }] },
      { order: 'id_raw', cv: 0.023722154164763583, extraMin: 212956, extraMax: 227740, byVictim: [{ victim: 'dist_size_cost', extra: 212956 }, { victim: 'cost_then_dist', extra: 220332 }, { victim: 'cheap_first', extra: 220332 }, { victim: 'far_only', extra: 227740 }] },
      { order: 'min_id', cv: 0.007130806550623157, extraMin: 473801, extraMax: 483257, byVictim: [{ victim: 'dist_size_cost', extra: 473801 }, { victim: 'cost_then_dist', extra: 479945 }, { victim: 'cheap_first', extra: 479945 }, { victim: 'far_only', extra: 483257 }] },
      { order: 'baseline', cv: 0.09577481650718427, extraMin: 74076, extraMax: 90644, byVictim: [{ victim: 'dist_size_cost', extra: 88768 }, { victim: 'cost_then_dist', extra: 74076 }, { victim: 'cheap_first', extra: 74076 }, { victim: 'far_only', extra: 90644 }] },
  ] },
  { case: 'Conv_Case1', family: 'conv', orders: [
      { order: 'p1', cv: 2.6136821030731674e-05, extraMin: 382592, extraMax: 382612, byVictim: [{ victim: 'dist_size_cost', extra: 382612 }, { victim: 'cost_then_dist', extra: 382592 }, { victim: 'cheap_first', extra: 382592 }, { victim: 'far_only', extra: 382612 }] },
      { order: 'capfit_id', cv: 0.039415979689227026, extraMin: 78056, extraMax: 86008, byVictim: [{ victim: 'dist_size_cost', extra: 78056 }, { victim: 'cost_then_dist', extra: 86008 }, { victim: 'cheap_first', extra: 86008 }, { victim: 'far_only', extra: 84712 }] },
      { order: 'id_raw', cv: 0.03467507257293804, extraMin: 73348, extraMax: 79952, byVictim: [{ victim: 'dist_size_cost', extra: 73348 }, { victim: 'cost_then_dist', extra: 79952 }, { victim: 'cheap_first', extra: 79952 }, { victim: 'far_only', extra: 77758 }] },
      { order: 'min_id', cv: 0.040543081624078596, extraMin: 1107476, extraMax: 1204274, byVictim: [{ victim: 'dist_size_cost', extra: 1107476 }, { victim: 'cost_then_dist', extra: 1204274 }, { victim: 'cheap_first', extra: 1204274 }, { victim: 'far_only', extra: 1113572 }] },
      { order: 'baseline', cv: 0.03467507257293804, extraMin: 73348, extraMax: 79952, byVictim: [{ victim: 'dist_size_cost', extra: 73348 }, { victim: 'cost_then_dist', extra: 79952 }, { victim: 'cheap_first', extra: 79952 }, { victim: 'far_only', extra: 77758 }] },
  ] },
  { case: 'FlashAttention_Case0', family: 'fa', orders: [
      { order: 'p1', cv: 0.0, extraMin: 48548, extraMax: 48548, byVictim: [{ victim: 'dist_size_cost', extra: 48548 }, { victim: 'cost_then_dist', extra: 48548 }, { victim: 'cheap_first', extra: 48548 }, { victim: 'far_only', extra: 48548 }] },
      { order: 'capfit_id', cv: 0.0, extraMin: 4444, extraMax: 4444, byVictim: [{ victim: 'dist_size_cost', extra: 4444 }, { victim: 'cost_then_dist', extra: 4444 }, { victim: 'cheap_first', extra: 4444 }, { victim: 'far_only', extra: 4444 }] },
      { order: 'id_raw', cv: 0.0, extraMin: 3904, extraMax: 3904, byVictim: [{ victim: 'dist_size_cost', extra: 3904 }, { victim: 'cost_then_dist', extra: 3904 }, { victim: 'cheap_first', extra: 3904 }, { victim: 'far_only', extra: 3904 }] },
      { order: 'min_id', cv: 0.011498341760702293, extraMin: 117520, extraMax: 120592, byVictim: [{ victim: 'dist_size_cost', extra: 117520 }, { victim: 'cost_then_dist', extra: 120592 }, { victim: 'cheap_first', extra: 120592 }, { victim: 'far_only', extra: 118288 }] },
      { order: 'baseline', cv: 0.0, extraMin: 3904, extraMax: 3904, byVictim: [{ victim: 'dist_size_cost', extra: 3904 }, { victim: 'cost_then_dist', extra: 3904 }, { victim: 'cheap_first', extra: 3904 }, { victim: 'far_only', extra: 3904 }] },
  ] },
  { case: 'FlashAttention_Case1', family: 'fa', orders: [
      { order: 'p1', cv: 0.0, extraMin: 245104, extraMax: 245104, byVictim: [{ victim: 'dist_size_cost', extra: 245104 }, { victim: 'cost_then_dist', extra: 245104 }, { victim: 'cheap_first', extra: 245104 }, { victim: 'far_only', extra: 245104 }] },
      { order: 'capfit_id', cv: 0.0, extraMin: 32920, extraMax: 32920, byVictim: [{ victim: 'dist_size_cost', extra: 32920 }, { victim: 'cost_then_dist', extra: 32920 }, { victim: 'cheap_first', extra: 32920 }, { victim: 'far_only', extra: 32920 }] },
      { order: 'id_raw', cv: 0.0, extraMin: 33152, extraMax: 33152, byVictim: [{ victim: 'dist_size_cost', extra: 33152 }, { victim: 'cost_then_dist', extra: 33152 }, { victim: 'cheap_first', extra: 33152 }, { victim: 'far_only', extra: 33152 }] },
      { order: 'min_id', cv: 0.05912410188313788, extraMin: 511024, extraMax: 575536, byVictim: [{ victim: 'dist_size_cost', extra: 511024 }, { victim: 'cost_then_dist', extra: 575536 }, { victim: 'cheap_first', extra: 575536 }, { victim: 'far_only', extra: 511536 }] },
      { order: 'baseline', cv: 0.0, extraMin: 33152, extraMax: 33152, byVictim: [{ victim: 'dist_size_cost', extra: 33152 }, { victim: 'cost_then_dist', extra: 33152 }, { victim: 'cheap_first', extra: 33152 }, { victim: 'far_only', extra: 33152 }] },
  ] },
  { case: 'Matmul_Case0', family: 'matmul', orders: [
      { order: 'p1', cv: 0.0, extraMin: 311296, extraMax: 311296, byVictim: [{ victim: 'dist_size_cost', extra: 311296 }, { victim: 'cost_then_dist', extra: 311296 }, { victim: 'cheap_first', extra: 311296 }, { victim: 'far_only', extra: 311296 }] },
      { order: 'capfit_id', cv: 0.0, extraMin: 34688, extraMax: 34688, byVictim: [{ victim: 'dist_size_cost', extra: 34688 }, { victim: 'cost_then_dist', extra: 34688 }, { victim: 'cheap_first', extra: 34688 }, { victim: 'far_only', extra: 34688 }] },
      { order: 'id_raw', cv: 0.0, extraMin: 34944, extraMax: 34944, byVictim: [{ victim: 'dist_size_cost', extra: 34944 }, { victim: 'cost_then_dist', extra: 34944 }, { victim: 'cheap_first', extra: 34944 }, { victim: 'far_only', extra: 34944 }] },
      { order: 'min_id', cv: 0.0, extraMin: 340224, extraMax: 340224, byVictim: [{ victim: 'dist_size_cost', extra: 340224 }, { victim: 'cost_then_dist', extra: 340224 }, { victim: 'cheap_first', extra: 340224 }, { victim: 'far_only', extra: 340224 }] },
      { order: 'baseline', cv: 0.0, extraMin: 34944, extraMax: 34944, byVictim: [{ victim: 'dist_size_cost', extra: 34944 }, { victim: 'cost_then_dist', extra: 34944 }, { victim: 'cheap_first', extra: 34944 }, { victim: 'far_only', extra: 34944 }] },
  ] },
  { case: 'Matmul_Case1', family: 'matmul', orders: [
      { order: 'p1', cv: 0.0, extraMin: 2818048, extraMax: 2818048, byVictim: [{ victim: 'dist_size_cost', extra: 2818048 }, { victim: 'cost_then_dist', extra: 2818048 }, { victim: 'cheap_first', extra: 2818048 }, { victim: 'far_only', extra: 2818048 }] },
      { order: 'capfit_id', cv: 0.0, extraMin: 460800, extraMax: 460800, byVictim: [{ victim: 'dist_size_cost', extra: 460800 }, { victim: 'cost_then_dist', extra: 460800 }, { victim: 'cheap_first', extra: 460800 }, { victim: 'far_only', extra: 460800 }] },
      { order: 'id_raw', cv: 0.0, extraMin: 460800, extraMax: 460800, byVictim: [{ victim: 'dist_size_cost', extra: 460800 }, { victim: 'cost_then_dist', extra: 460800 }, { victim: 'cheap_first', extra: 460800 }, { victim: 'far_only', extra: 460800 }] },
      { order: 'min_id', cv: 0.0, extraMin: 2748544, extraMax: 2748544, byVictim: [{ victim: 'dist_size_cost', extra: 2748544 }, { victim: 'cost_then_dist', extra: 2748544 }, { victim: 'cheap_first', extra: 2748544 }, { victim: 'far_only', extra: 2748544 }] },
      { order: 'baseline', cv: 0.0, extraMin: 460800, extraMax: 460800, byVictim: [{ victim: 'dist_size_cost', extra: 460800 }, { victim: 'cost_then_dist', extra: 460800 }, { victim: 'cheap_first', extra: 460800 }, { victim: 'far_only', extra: 460800 }] },
  ] },
]
