// AUTO-GENERATED by tmp/gen_data.py — do not edit by hand.

export type PortfolioStep = { iter: string; desc: string; wins: number; losses: number; ties: number }

export const PORTFOLIO: PortfolioStep[] = [
  { iter: 'iter034', desc: 'capfit_p123', wins: 8, losses: 10, ties: 0 },
  { iter: 'iter035', desc: 'p3_time_select', wins: 10, losses: 8, ties: 0 },
  { iter: 'iter036', desc: 'p2_time_bestfit', wins: 11, losses: 7, ties: 0 },
  { iter: 'iter037', desc: 'p3_prefetch_grid', wins: 12, losses: 6, ties: 0 },
  { iter: 'iter038', desc: 'id_raw_candidate', wins: 13, losses: 5, ties: 0 },
]

export const PORTFOLIO_DENOM = 18
