// AUTO-GENERATED by tmp/gen_data.py — do not edit by hand.

export type CorrRow = { case: string; phiExtra: number; peakExtra: number; phiTime: number; n: number }

export const CORRELATION: CorrRow[] = [
  { case: 'Conv_Case0', phiExtra: 0.6, peakExtra: 0.6, phiTime: 0.6, n: 6 },
  { case: 'Conv_Case1', phiExtra: 0.54077263383169, peakExtra: 0.29325153374233126, phiTime: 0.6854691662401694, n: 17 },
  { case: 'FlashAttention_Case0', phiExtra: 0.20723486421214424, peakExtra: 0.43120425659407785, phiTime: 0.24754901960784315, n: 17 },
  { case: 'FlashAttention_Case1', phiExtra: 0.4696506094275222, peakExtra: 0.498156488904147, phiTime: 0.5196078431372549, n: 17 },
  { case: 'Matmul_Case0', phiExtra: 0.4260283184553522, peakExtra: 0.3912526268339324, phiTime: 0.5702024370334147, n: 17 },
  { case: 'Matmul_Case1', phiExtra: 0.4081137853552264, peakExtra: 0.19704433497536947, phiTime: 0.6045372074354267, n: 17 },
  { case: 'ALL', phiExtra: 0.9574714615363904, peakExtra: 0.9548522493441016, phiTime: 0.954725530253589, n: 91 },
]
