// AUTO-GENERATED by tmp/gen_data.py — do not edit by hand.

export type CacheName = 'L1' | 'UB' | 'L0A' | 'L0B' | 'L0C'
export type BoundClass = 'capacity_bound' | 'order_reachable'
export type WorkingSetRow = {
  case: string
  family: 'matmul' | 'fa' | 'conv'
  cache: CacheName
  capacity: number
  minPeak: number
  ratio: number
  boundClass: BoundClass
  cleanFracAtPeak: number
}

export const WORKING_SET: WorkingSetRow[] = [
  { case: 'Conv_Case0', family: 'conv', cache: 'L1', capacity: 4096, minPeak: 6912, ratio: 1.6875, boundClass: 'capacity_bound', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case0', family: 'conv', cache: 'UB', capacity: 1024, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case0', family: 'conv', cache: 'L0A', capacity: 256, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case0', family: 'conv', cache: 'L0B', capacity: 256, minPeak: 96, ratio: 0.375, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case0', family: 'conv', cache: 'L0C', capacity: 512, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case1', family: 'conv', cache: 'L1', capacity: 4096, minPeak: 14040, ratio: 3.427734375, boundClass: 'capacity_bound', cleanFracAtPeak: 0.8415954415954416 },
  { case: 'Conv_Case1', family: 'conv', cache: 'UB', capacity: 1024, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case1', family: 'conv', cache: 'L0A', capacity: 256, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case1', family: 'conv', cache: 'L0B', capacity: 256, minPeak: 96, ratio: 0.375, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Conv_Case1', family: 'conv', cache: 'L0C', capacity: 512, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case0', family: 'fa', cache: 'L1', capacity: 4096, minPeak: 3328, ratio: 0.8125, boundClass: 'order_reachable', cleanFracAtPeak: 0.9230769230769231 },
  { case: 'FlashAttention_Case0', family: 'fa', cache: 'UB', capacity: 1024, minPeak: 1428, ratio: 1.39453125, boundClass: 'capacity_bound', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case0', family: 'fa', cache: 'L0A', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case0', family: 'fa', cache: 'L0B', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case0', family: 'fa', cache: 'L0C', capacity: 512, minPeak: 256, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case1', family: 'fa', cache: 'L1', capacity: 4096, minPeak: 5376, ratio: 1.3125, boundClass: 'capacity_bound', cleanFracAtPeak: 0.9523809523809523 },
  { case: 'FlashAttention_Case1', family: 'fa', cache: 'UB', capacity: 1024, minPeak: 2468, ratio: 2.41015625, boundClass: 'capacity_bound', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case1', family: 'fa', cache: 'L0A', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case1', family: 'fa', cache: 'L0B', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'FlashAttention_Case1', family: 'fa', cache: 'L0C', capacity: 512, minPeak: 256, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case0', family: 'matmul', cache: 'L1', capacity: 4096, minPeak: 9216, ratio: 2.25, boundClass: 'capacity_bound', cleanFracAtPeak: 1.0 },
  { case: 'Matmul_Case0', family: 'matmul', cache: 'UB', capacity: 1024, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case0', family: 'matmul', cache: 'L0A', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case0', family: 'matmul', cache: 'L0B', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case0', family: 'matmul', cache: 'L0C', capacity: 512, minPeak: 256, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case1', family: 'matmul', cache: 'L1', capacity: 4096, minPeak: 34816, ratio: 8.5, boundClass: 'capacity_bound', cleanFracAtPeak: 1.0 },
  { case: 'Matmul_Case1', family: 'matmul', cache: 'UB', capacity: 1024, minPeak: 0, ratio: 0.0, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case1', family: 'matmul', cache: 'L0A', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case1', family: 'matmul', cache: 'L0B', capacity: 256, minPeak: 128, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
  { case: 'Matmul_Case1', family: 'matmul', cache: 'L0C', capacity: 512, minPeak: 256, ratio: 0.5, boundClass: 'order_reachable', cleanFracAtPeak: 0.0 },
]
