"""Sync paper numbers, tables, and figure copies from tracked CSV outputs."""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "results" / "paper" / "PAPER_NUMBERS.yml"
TABLE_DIR = ROOT / "paper" / "assets" / "tables"
FIGURE_DIR = ROOT / "paper" / "assets" / "figures"


def main() -> None:
    manifest = yaml.safe_load(MANIFEST.read_text())
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    numbers = [_compute_number(row) for row in manifest["numbers"]]
    _write_numbers_tex(numbers)
    _write_headline_tables()
    _copy_figures(manifest.get("figures", []))

    print("Synced paper artifacts:")
    print(f"  {TABLE_DIR / 'numbers.tex'}")
    print(f"  {TABLE_DIR / 'headline_results.tex'}")
    print(f"  {TABLE_DIR / 'headline_summary.tex'}")
    print(f"  {TABLE_DIR / 'remaining_losses.tex'}")
    print(f"  {FIGURE_DIR}")


def _read_csv(path: str) -> pd.DataFrame:
    return pd.read_csv(ROOT / path)


def _filtered(df: pd.DataFrame, query: str | None) -> pd.DataFrame:
    return df.query(query) if query else df


def _compute_number(row: dict[str, Any]) -> dict[str, str]:
    df = _filtered(_read_csv(row["source_csv"]), row.get("filter"))
    operation = row["operation"]
    column = row.get("column")

    if operation == "count":
        value: Any = len(df)
    elif operation == "value":
        if column is None:
            raise ValueError(f"{row['id']} uses value without column")
        if len(df) != 1:
            raise ValueError(f"{row['id']} expected one row, found {len(df)}")
        value = df.iloc[0][column]
    elif operation == "max":
        if column is None:
            raise ValueError(f"{row['id']} uses max without column")
        value = df[column].max()
    elif operation == "sequence":
        if column is None:
            raise ValueError(f"{row['id']} uses sequence without column")
        sep = row.get("separator", ",")
        value = sep.join(str(int(v)) if float(v).is_integer() else str(v) for v in df[column])
    else:
        raise ValueError(f"Unknown operation for {row['id']}: {operation}")

    formatted = _format_value(value, row.get("format", "raw"))
    expected = row.get("expected")
    if expected is not None and formatted != str(expected):
        raise AssertionError(f"{row['id']}: computed {formatted}, expected {expected}")
    return {"id": row["id"], "macro": row["tex_macro"], "value": formatted}


def _format_value(value: Any, fmt: str) -> str:
    if fmt == "raw":
        return str(value)
    if fmt == "int":
        return str(int(round(float(value))))
    if fmt == "float1":
        return f"{float(value):.1f}"
    if fmt == "float4":
        return f"{float(value):.4f}"
    if fmt == "float5":
        return f"{float(value):.5f}"
    if fmt == "percent2":
        return f"{float(value) * 100:.2f}\\%"
    raise ValueError(f"Unknown format: {fmt}")


def _write_numbers_tex(numbers: list[dict[str, str]]) -> None:
    lines = [
        "% Auto-generated by scripts/paper/sync_paper_artifacts.py.",
        "% Do not edit by hand; update results/paper/PAPER_NUMBERS.yml instead.",
        "",
    ]
    lines.extend(f"\\newcommand{{\\{row['macro']}}}{{{row['value']}}}" for row in numbers)
    (TABLE_DIR / "numbers.tex").write_text("\n".join(lines) + "\n")


def _write_headline_tables() -> None:
    headline = _read_csv("results/paper/e1_headline.csv")
    headline = headline[
        [
            "case",
            "problem",
            "result",
            "ours_extra",
            "base_extra",
            "ours_time",
            "base_time",
        ]
    ]
    _write_tabular(
        TABLE_DIR / "headline_results.tex",
        ["Case", "P", "Result", "Ours extra", "Base extra", "Ours time", "Base time"],
        headline.values.tolist(),
    )

    scored = _read_csv("results/paper/e1_headline.csv").assign(
        time_ratio=lambda df: df["ours_time"] / df["base_time"],
        extra_delta=lambda df: df["ours_extra"] - df["base_extra"],
    )
    problem_names = {1: "P1 residency", 2: "P2 spill bytes", 3: "P3 time"}
    summary_rows = []
    for problem, group in scored.groupby("problem", sort=True):
        summary_rows.append(
            [
                problem_names[int(problem)],
                len(group),
                int(group["result"].eq("WIN").sum()),
                int(group["result"].eq("LOSS").sum()),
                f"{group['time_ratio'].mean():.2f}",
                _signed_int(group["extra_delta"].mean()),
            ]
        )
    summary_rows.append(
        [
            "All rows",
            len(scored),
            int(scored["result"].eq("WIN").sum()),
            int(scored["result"].eq("LOSS").sum()),
            f"{scored['time_ratio'].mean():.2f}",
            _signed_int(scored["extra_delta"].mean()),
        ]
    )
    _write_tabular(
        TABLE_DIR / "headline_summary.tex",
        ["Target", "Rows", "Wins", "Losses", "Mean time/base", "Mean extra delta"],
        summary_rows,
    )

    losses = headline[headline["result"].eq("LOSS")].copy()
    _write_tabular(
        TABLE_DIR / "remaining_losses.tex",
        ["Case", "P", "Ours extra", "Base extra", "Ours time", "Base time"],
        losses[["case", "problem", "ours_extra", "base_extra", "ours_time", "base_time"]]
        .values
        .tolist(),
    )


def _write_tabular(path: Path, headers: list[str], rows: list[list[Any]]) -> None:
    lines = [
        "% Auto-generated by scripts/paper/sync_paper_artifacts.py.",
        "\\begin{tabular}{" + "l" * len(headers) + "}",
        "\\toprule",
        " & ".join(_tex(v) for v in headers) + r" \\",
        "\\midrule",
    ]
    lines.extend(" & ".join(_tex(v) for v in row) + r" \\" for row in rows)
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    path.write_text("\n".join(lines))


def _tex(value: Any) -> str:
    text = str(value)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
    )


def _signed_int(value: float) -> str:
    rounded = int(round(value))
    return f"{rounded:+,}" if rounded else "0"


def _copy_figures(figures: list[dict[str, str]]) -> None:
    for item in figures:
        src = ROOT / item["source"]
        dst = ROOT / item["target"]
        if not src.exists():
            raise FileNotFoundError(src)
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


if __name__ == "__main__":
    main()
